// Code generated by "stringer -type=KnownPath"; DO NOT EDIT.

package paths

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Status-0]
	_ = x[QueryDNS-1]
	_ = x[Ping-2]
	_ = x[Pprof-3]
	_ = x[Prefs-4]
	_ = x[Logs-5]
	_ = x[DriveShares-6]
	_ = x[DNSConfig-7]
	_ = x[ServeConfig-8]
	_ = x[AppConnRoutes-9]
	_ = x[Goroutines-10]
	_ = x[Hosts-11]
	_ = x[PeerMap-12]
	_ = x[BusEvents-13]
	_ = x[End-14]
}

const _KnownPath_name = "StatusQueryDNSPingPprofPrefsLogsDriveSharesDNSConfigServeConfigAppConnRoutesGoroutinesHostsPeerMapBusEventsEnd"

var _KnownPath_index = [...]uint8{0, 6, 14, 18, 23, 28, 32, 43, 52, 63, 76, 86, 91, 98, 107, 110}

func (i KnownPath) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KnownPath_index)-1 {
		return "KnownPath(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KnownPath_name[_KnownPath_index[idx]:_KnownPath_index[idx+1]]
}
