// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package utils

import (
	"context"
	"sync"
	"tailscale.com/client/tailscale/v2"
)

// Ensure, that TailscaleClientMock does implement TailscaleClient.
// If this is not the case, regenerate this file with moq.
var _ TailscaleClient = &TailscaleClientMock{}

// TailscaleClientMock is a mock implementation of TailscaleClient.
//
//	func TestSomethingThatUsesTailscaleClient(t *testing.T) {
//
//		// make and configure a mocked TailscaleClient
//		mockedTailscaleClient := &TailscaleClientMock{
//			GenerateDeviceKeyFunc: func(contextMoqParam context.Context, s string, strings []string) (*tailscale.Key, error) {
//				panic("mock out the GenerateDeviceKey method")
//			},
//			GetDevicesWithTagFunc: func(s string) ([]tailscale.Device, error) {
//				panic("mock out the GetDevicesWithTag method")
//			},
//		}
//
//		// use mockedTailscaleClient in code that requires TailscaleClient
//		// and then make assertions.
//
//	}
type TailscaleClientMock struct {
	// GenerateDeviceKeyFunc mocks the GenerateDeviceKey method.
	GenerateDeviceKeyFunc func(contextMoqParam context.Context, s string, strings []string) (*tailscale.Key, error)

	// GetDevicesWithTagFunc mocks the GetDevicesWithTag method.
	GetDevicesWithTagFunc func(s string) ([]tailscale.Device, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateDeviceKey holds details about calls to the GenerateDeviceKey method.
		GenerateDeviceKey []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Strings is the strings argument value.
			Strings []string
		}
		// GetDevicesWithTag holds details about calls to the GetDevicesWithTag method.
		GetDevicesWithTag []struct {
			// S is the s argument value.
			S string
		}
	}
	lockGenerateDeviceKey sync.RWMutex
	lockGetDevicesWithTag sync.RWMutex
}

// GenerateDeviceKey calls GenerateDeviceKeyFunc.
func (mock *TailscaleClientMock) GenerateDeviceKey(contextMoqParam context.Context, s string, strings []string) (*tailscale.Key, error) {
	if mock.GenerateDeviceKeyFunc == nil {
		panic("TailscaleClientMock.GenerateDeviceKeyFunc: method is nil but TailscaleClient.GenerateDeviceKey was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		Strings         []string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		Strings:         strings,
	}
	mock.lockGenerateDeviceKey.Lock()
	mock.calls.GenerateDeviceKey = append(mock.calls.GenerateDeviceKey, callInfo)
	mock.lockGenerateDeviceKey.Unlock()
	return mock.GenerateDeviceKeyFunc(contextMoqParam, s, strings)
}

// GenerateDeviceKeyCalls gets all the calls that were made to GenerateDeviceKey.
// Check the length with:
//
//	len(mockedTailscaleClient.GenerateDeviceKeyCalls())
func (mock *TailscaleClientMock) GenerateDeviceKeyCalls() []struct {
	ContextMoqParam context.Context
	S               string
	Strings         []string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		Strings         []string
	}
	mock.lockGenerateDeviceKey.RLock()
	calls = mock.calls.GenerateDeviceKey
	mock.lockGenerateDeviceKey.RUnlock()
	return calls
}

// GetDevicesWithTag calls GetDevicesWithTagFunc.
func (mock *TailscaleClientMock) GetDevicesWithTag(s string) ([]tailscale.Device, error) {
	if mock.GetDevicesWithTagFunc == nil {
		panic("TailscaleClientMock.GetDevicesWithTagFunc: method is nil but TailscaleClient.GetDevicesWithTag was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockGetDevicesWithTag.Lock()
	mock.calls.GetDevicesWithTag = append(mock.calls.GetDevicesWithTag, callInfo)
	mock.lockGetDevicesWithTag.Unlock()
	return mock.GetDevicesWithTagFunc(s)
}

// GetDevicesWithTagCalls gets all the calls that were made to GetDevicesWithTag.
// Check the length with:
//
//	len(mockedTailscaleClient.GetDevicesWithTagCalls())
func (mock *TailscaleClientMock) GetDevicesWithTagCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockGetDevicesWithTag.RLock()
	calls = mock.calls.GetDevicesWithTag
	mock.lockGetDevicesWithTag.RUnlock()
	return calls
}
