version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - sh -c "cd web-ui && BUILD_VERSION=v{{.Version}} npm run build"

builds:
  - id: tsymbiote
    binary: tsymbiote
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X github.com/dhouti/tsymbiote/cmd.buildVersion=v{{.Version}}"

dockers_v2:
  - id: adapter
    dockerfile: Dockerfile.adapter
    images:
    - ghcr.io/dhouti/tsymbiote-adapter
    platforms:
    - linux/amd64
    - linux/arm64

  - id: webui
    dockerfile: Dockerfile.webui
    images:
    - ghcr.io/dhouti/tsymbiote-webui
    platforms:
    - linux/amd64
    - linux/arm64
  
  - id: operator
    dockerfile: Dockerfile.operator
    images:
    - ghcr.io/dhouti/tsymbiote-operator
    build_args:
      TSYMBIOTE_WEBUI_IMAGE: ghcr.io/dhouti/tsymbiote-webui:v{{.Version}}
      TSYMBIOTE_ADAPTER_IMAGE: ghcr.io/dhouti/tsymbiote-adapter:v{{.Version}}
    platforms:
    - linux/amd64
    - linux/arm64
    # Not going to use the copy-binary method for this.
    extra_files:
    - pkg/
    - operator/
    - go.mod
    - go.sum

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
